services:
  template.api:
    image: template
    container_name: template.api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    #      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8080"
    #      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - template.db
  
  template.db:
    image: postgres:latest
    container_name: template.db
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  template.seq:
    image: datalust/seq:latest
    container_name: template.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
  
  template.redis:
    image: redis:latest
    container_name: template.redis
    restart: always
    ports:
      - "6379:6379"
