# This is a generated file. Not intended for manual editing.
services:
  template.api:
    build:
      context: "/run/media/alex/mass_storage/Repos/Template.Api"
      dockerfile: "Presentation/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "template:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/run/media/alex/mass_storage/Repos/Template.Api/Presentation:/app:rw"
    - "/run/media/alex/mass_storage/Repos/Template.Api:/src:rw"
    - "/home/alex/.nuget/packages:/home/app/.nuget/packages"
    - "/home/alex/.local/share/JetBrains/RiderRemoteDebugger/2025.1.2/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/alex/.local/share/JetBrains/Toolbox/apps/rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/alex/.cache/JetBrains/Rider2025.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_6_04_19_51_05:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
