# This is a generated file. Not intended for manual editing.
services:
  template.api:
    build:
      context: "/mnt/mass_storage/Repos/CleanArchitecture-Template/Template"
      dockerfile: "Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "template:dev"
    ports: []
    volumes:
    - "/mnt/mass_storage/Repos/CleanArchitecture-Template/Template/Presentation:/app:rw"
    - "/mnt/mass_storage/Repos/CleanArchitecture-Template/Template:/src:rw"
    - "/home/alex/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
