# This is a generated file. Not intended for manual editing.
services:
  template.api:
    build:
      context: "X:\\Repos\\Template\\Template"
      dockerfile: "Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "template:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "X:\\Repos\\Template\\Template\\Api:/app:rw"
    - "X:\\Repos\\Template\\Template:/src:rw"
    - "C:\\Users\\realb\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\realb\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\realb\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\realb\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_4_17_19_51_22:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
