# This is a generated file. Not intended for manual editing.
services:
  template.api:
    build:
      context: "X:\\Repos\\Template\\Template"
      dockerfile: "Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "template:dev"
    ports: []
    volumes:
    - "X:\\Repos\\Template\\Template\\Api:/app:rw"
    - "X:\\Repos\\Template\\Template:/src:rw"
    - "C:\\Users\\realb\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
